siteTitle = "jmsmrgn.com"
siteDescr = "front-end developer"
siteAuthor = "James Morgan"

siteEmailUrl = "mailto:mail@jmsmrgn.com"
siteTwitterUrl = "https://twitter.com/jmsmrgn"
siteGithubUrl = "https://github.com/jmsmrgn"
siteCodePenUrl = "http://codepen.io/jmsmrgn/"

linkPrefix = "/lumen"
